allowBuilds:
  '@scarf/scarf': true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@copilotkit/a2ui-renderer@1.71.0'
  - '@copilotkit/core@1.71.0'
  - '@copilotkit/react-core@1.71.0'
  - '@copilotkit/react-ui@1.71.0'
  - '@copilotkit/runtime-client-gql@1.71.0'
  - '@copilotkit/runtime@1.71.0'
  - '@copilotkit/shared@1.71.0'
  - '@copilotkit/web-components@1.71.0'
  - '@copilotkit/web-inspector@1.71.0'
  - openai@7.13.0
  - react-dom@19.3.0
  - react@19.3.0
  - scheduler@0.28.0
